import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useState} from 'react';

export default function Home() {

    const [count, setCount] = useState(0);
    const [todoList, setTodoList] = useState(["apple", "banana", "tamato"]);
    const [addTodo, setAddTodo] = useState("");
    const [deleteTodo, setDeleteValue] = useState("");
    const [editabledTodo, setEditabledTodo] = useState(null);

    const editTask = (item, index) => {
        setEditabledTodo(index);
    }

    const handleChange = e => {

        let newTodoList = [...todoList];
        newTodoList[editabledTodo] = e.target.value;
        setTodoList(newTodoList);
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello there </h1>
        <p>count : {count}</p>
        <button onClick={() => setCount(prev => prev + 1)}>Ajouter</button>

        <input onChange={(e) => setAddTodo(addTodo => e.target.value)}></input>
        <button onClick={() => setTodoList(todoList => [...todoList, addTodo])}>Add todo</button>

        { todoList.length > 0 && (
            todoList.map((todo,i) =>{
                return(
                    <div key = {i}>

                        <input type = "text" onChange={(e) => handleChange(e)} value={todo} disabled={editabledTodo === i ? false :true}/>

                        <button onClick={() => editTask(todo,i)}>Edit</button>
                        <button onClick={()=>setTodoList(prevArray => prevArray.filter((item, index) => index !== i))}>Delete</button>
                    </div>
                )
                
            })
        )}
    

      </main>

    </div>
  )
}



